use [$(dbname)]
go

CREATE TABLE [dbo].[TblCustomerProfileHistory]
(
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	CustomerID bigint not null,
	FirstName varchar(50) not null,
	MiddleName varchar(50) Null,
	LastName varchar(50) not null,
	HomeAddress1 varchar(500) Not Null,
	HomeAddress2 varchar(500) Null,
	HomeCity varchar(200) Not Null,
	[HomeState] varchar(200) Not Null,
	[HomeZipCode] varchar(100) Not Null,
	[HomeCountry] varchar(100) Not Null,
	PhoneOffice varchar(50) Null,
	PhoneCell varchar(50) Null,
	PhoneHome varchar(50) Null,
	EMail1 varchar(100) Null,
	EMail2 varchar(100) Null,
	Picture varchar(500) Null,
	--AddedMethod varchar(50),
	DOB SmallDatetime Null,			
	DefaultRoleID bigint Null,
	--DigitalSignature varchar(2000) Null,
	PhoneOfficeExtension varchar(50) Null,
	SSN  varchar(255) Null,

	DisplayID bigint Null,
	BillingAddress1 varchar(500) Null,
	BillingAddress2 varchar(500) Null ,
	BillingCity varchar(200) Null,
	[BillingState] varchar(200) Null,
	[BillingZipCode] varchar(100) Null,
	[BillingCountry] varchar(100) Null,
	--ContactMethod varchar(50) Null,	
	Height nvarchar(40) Null,
	[Weight] float(53) Null,
	Gender nvarchar(40) Null,
	Race varchar(500) Null,		
	--CollectionMode varchar(50) Null,
	--IsMailingList bit,
	--IsDirectMail bit,
	--IsSpecialOffer bit,
	TrackingMarketingID varchar(500) Null,
	AddedByRoleID bigint Null,
	--SignInSource varchar(50),
	--AdvocateID bigint,
	Employer varchar(500) Null,
	EmergencyContactName varchar(200) Null,
	EmergencyContactRelationship varchar(200) Null,
	EmergencyContactPhoneNumber varchar(20) Null, 
	DoNotContactReasonId bigint Null,
	DoNotContactReasonNotesId bigint Null,
	RequestNewsLetter bit Not Null,
	--UserDefined1 varchar(1000),
	EmployeeId varchar(100) Null,
	InsuranceId varchar(100) Null,
	PreferredLanguage varchar(250) Null,
	BestTimeToCall bigint Null,
	Waist decimal(18,2) Null,
	HICN varchar(100 ) Null,
	EnableTexting bit Not Null,
	MedicareAdvantageNumber varchar(255) Null,
	Tag varchar(255) Null,
	MedicareAdvantagePlanName varchar(255) Null,
	IsEligble bit Null,
	LanguageId bigint Null,
	LabId bigint Null,
	Copay varchar(50) Not Null,
	Lpi varchar(50) Not Null,
	Market varchar(255) Not Null,
	Mrn varchar(255) Not Null,
	GroupName varchar(255)  Not Null,
	IsIncorrectPhoneNumber bit Not Null,
	IsLanguageBarrier bit Not Null,
	DoNotContactTypeId bigint Null,
	EnableVoiceMail bit Not Null,
	AdditionalField1 varchar(512) Null,
	AdditionalField2 varchar(512) Null,
	AdditionalField3 varchar(512) Null,
	AdditionalField4 varchar(512) Null,
	ActivityId bigint Null,
	DoNotContactUpdateDate datetime Null,
	DateCreated Datetime Not Null,
	CreatedBy bigInt Not Null,
	CONSTRAINT PK_TblCustomerProfileHistory PRIMARY KEY ([Id]),	
	CONSTRAINT FK_TblCustomerProfileHistory_TblCustomerProfile FOREIGN KEY (CustomerId) REFERENCES [TblCustomerProfile](CustomerId),
	CONSTRAINT FK_TblCustomerProfileHistory_TblOrganizationRoleUser FOREIGN KEY (CreatedBy) REFERENCES [TblOrganizationRoleUser](OrganizationRoleUserId),
)
