USE [$(dbname)]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TblUserNpiInfo](
	[UserID] [bigint] NOT NULL,
	[Npi] [varchar](255) NOT NULL,
 CONSTRAINT [PK_TblUserNpiInfo] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[TblUserNpiInfo]  WITH CHECK ADD  CONSTRAINT [FK_TblUserNpiInfo_TblUser] FOREIGN KEY([UserID])
REFERENCES [dbo].[TblUser] ([UserID])
GO

ALTER TABLE [dbo].[TblUserNpiInfo] CHECK CONSTRAINT [FK_TblUserNpiInfo_TblUser]
GO


