USE [$(dbName)]
GO


--DROP STATISTICS
IF EXISTS (SELECT * FROM SYS.STATS WHERE NAME = N'STAT_TblCustomerTag_Tag_CustId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP STATISTICS [dbo].[TblCustomerTag].[STAT_TblCustomerTag_Tag_CustId]
GO

IF EXISTS (SELECT * FROM SYS.STATS WHERE NAME = N'STAT_TblCustomerTag_CustTagId_Tag' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP STATISTICS [dbo].[TblCustomerTag].[STAT_TblCustomerTag_CustTagId_Tag]
GO

IF EXISTS (SELECT * FROM SYS.STATS WHERE NAME = N'STAT_TblCustomerTag_CustId_CustTagId_Tag' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP STATISTICS [dbo].[TblCustomerTag].[STAT_TblCustomerTag_CustId_CustTagId_Tag]
GO

--DROP INDEXES
IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_CId_CTId_T' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_CId_CTId_T] ON [dbo].[TblCustomerTag]
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_CustomerId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_CustomerId] ON [dbo].[TblCustomerTag]
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_IActi_CId_CTId_INCL_Tag_DCrea_DModi_CBORUId_MBORUId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_IActi_CId_CTId_INCL_Tag_DCrea_DModi_CBORUId_MBORUId] ON [dbo].[TblCustomerTag]
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_IActi_Tag_CId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_IActi_Tag_CId] ON [dbo].[TblCustomerTag]
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_K2_3' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_K2_3] ON [dbo].[TblCustomerTag]
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_K2_K3' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_K2_K3] ON [dbo].[TblCustomerTag]
GO

IF EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_K3_K2' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
DROP INDEX [IX_TblCustomerTag_K3_K2] ON [dbo].[TblCustomerTag]
GO


--ALTER COLUMN
ALTER TABLE TblCustomerTag
ALTER COLUMN Tag NVARCHAR(255)
GO


--CREATE STATISTICS
IF NOT EXISTS (SELECT * FROM SYS.STATS WHERE NAME = N'STAT_TblCustomerTag_Tag_CustId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE STATISTICS [STAT_TblCustomerTag_Tag_CustId] ON [dbo].[TblCustomerTag]([Tag], [CustomerId])
GO

IF NOT EXISTS (SELECT * FROM SYS.STATS WHERE NAME = N'STAT_TblCustomerTag_CustTagId_Tag' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE STATISTICS [STAT_TblCustomerTag_CustTagId_Tag] ON [dbo].[TblCustomerTag]([CustomerTagId], [Tag])
GO

IF NOT EXISTS (SELECT * FROM SYS.STATS WHERE NAME = N'STAT_TblCustomerTag_CustId_CustTagId_Tag' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE STATISTICS [STAT_TblCustomerTag_CustId_CustTagId_Tag] ON [dbo].[TblCustomerTag]([CustomerId], [CustomerTagId], [Tag])
GO


--CREATE INDEXES
IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_CId_CTId_T' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_CId_CTId_T] ON [dbo].[TblCustomerTag]
(
	[CustomerId] ASC,
	[CustomerTagId] ASC,
	[Tag] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_CustomerId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_CustomerId] ON [dbo].[TblCustomerTag]
(
	[CustomerId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_IActi_CId_CTId_INCL_Tag_DCrea_DModi_CBORUId_MBORUId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_IActi_CId_CTId_INCL_Tag_DCrea_DModi_CBORUId_MBORUId] ON [dbo].[TblCustomerTag]
(
	[IsActive] ASC,
	[CustomerId] ASC,
	[CustomerTagId] ASC
)
INCLUDE ( 	[Tag],
	[DateCreated],
	[DateModified],
	[CreatedByOrgRoleUserId],
	[ModifiedByOrgRoleUserId]) WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_IActi_Tag_CId' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_IActi_Tag_CId] ON [dbo].[TblCustomerTag]
(
	[IsActive] ASC,
	[Tag] ASC,
	[CustomerId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_K2_3' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_K2_3] ON [dbo].[TblCustomerTag]
(
	[CustomerId] ASC
)
INCLUDE ( 	[Tag]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_K2_K3' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_K2_K3] ON [dbo].[TblCustomerTag]
(
	[CustomerId] ASC,
	[Tag] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO

IF NOT EXISTS (SELECT * FROM SYS.INDEXES WHERE NAME = N'IX_TblCustomerTag_K3_K2' AND OBJECT_ID = OBJECT_ID(N'[dbo].[TblCustomerTag]'))
CREATE NONCLUSTERED INDEX [IX_TblCustomerTag_K3_K2] ON [dbo].[TblCustomerTag]
(
	[Tag] ASC,
	[CustomerId] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
GO