
USE [$(dbName)]
Go

if not Exists (select EmailTemplateId from TblEmailTemplate where EmailTitle = 'PurchaseShippingNotification')
begin
	INSERT INTO [TblEmailTemplate]
			   ([EmailTitle],[EmailSubject],[EmailBody],[DateCreated],[DateModified])
	VALUES
	('PurchaseShippingNotification','Purchase Shipping Notification' 
		,'<table width="600" cellpadding="0" cellspacing="0" border="1" style="border-collapse: collapse;    border-color: black;">    <tr>        <td style="vertical-align: top;">            <table width="600" cellpadding="2" cellspacing="0" border="0" style="font-family: Arial">                <tr>                    <td style="height: 100px">                        <table width="600" cellpadding="2" cellspacing="0" border="0">                            <tr>                                <td style="width: 250px">                                    <img src="@Model.EmailCommunicationBaseInfo.EmailNotificationLogoRelativePath" />                                </td>                                <td align="right" style="color: #47A942; width: 250px">                                    Purchase Shipping Notification &nbsp;                                </td>                            </tr>                        </table>                    </td>                </tr>                <tr>                    <td class="normaltxt_pw" style="font-size: 13px">                        Hi,<br />                        <br />                        <b>@Model.CustomerName</b>(@Model.CustomerId) has purchased shipping of his/her results for the following event.                        <br />                        <br />                        <table cellspacing="0" border="1">                            <tr>                                <td>                                    Event Id                                </td>                                <td>                                    @Model.EventId                                </td>                            </tr>                            <tr>                                <td>                                    Event Date                                </td>                                <td>                                    @Model.EventDate.ToString("MM/dd/yyyy")                                </td>                            </tr>                            <tr>                                <td>                                    Event Location                                </td>                                <td>                                    @Model.AddressOfVenue.ToString()                                </td>                            </tr>                                                    </table>                    </td>                </tr>                <tr>                    <td>                        <hr style="float: left; height: 3px; width: 100%; color: #000; background-color: #000" />                    </td>                </tr>                <tr>                    <td class="normaltxt_pw" style="font-size: 12px;">                        - @Model.EmailCommunicationBaseInfo.CompanyName <span>Team</span>                    </td>                </tr>            </table>        </td>    </tr></table>'
		,getDate(),getDate())

end
else
begin
	update TblEmailTemplate 
	set [EmailSubject] = 'Purchase Shipping Notification'
	,[EmailBody] = '<table width="600" cellpadding="0" cellspacing="0" border="1" style="border-collapse: collapse;    border-color: black;">    <tr>        <td style="vertical-align: top;">            <table width="600" cellpadding="2" cellspacing="0" border="0" style="font-family: Arial">                <tr>                    <td style="height: 100px">                        <table width="600" cellpadding="2" cellspacing="0" border="0">                            <tr>                                <td style="width: 250px">                                    <img src="@Model.EmailCommunicationBaseInfo.EmailNotificationLogoRelativePath" />                                </td>                                <td align="right" style="color: #47A942; width: 250px">                                    Purchase Shipping Notification &nbsp;                                </td>                            </tr>                        </table>                    </td>                </tr>                <tr>                    <td class="normaltxt_pw" style="font-size: 13px">                        Hi,<br />                        <br />                        <b>@Model.CustomerName</b>(@Model.CustomerId) has purchased shipping of his/her results for the following event.                        <br />                        <br />                        <table cellspacing="0" border="1">                            <tr>                                <td>                                    Event Id                                </td>                                <td>                                    @Model.EventId                                </td>                            </tr>                            <tr>                                <td>                                    Event Date                                </td>                                <td>                                    @Model.EventDate.ToString("MM/dd/yyyy")                                </td>                            </tr>                            <tr>                                <td>                                    Event Location                                </td>                                <td>                                    @Model.AddressOfVenue.ToString()                                </td>                            </tr>                                                    </table>                    </td>                </tr>                <tr>                    <td>                        <hr style="float: left; height: 3px; width: 100%; color: #000; background-color: #000" />                    </td>                </tr>                <tr>                    <td class="normaltxt_pw" style="font-size: 12px;">                        - @Model.EmailCommunicationBaseInfo.CompanyName <span>Team</span>                    </td>                </tr>            </table>        </td>    </tr></table>'
	where EmailTitle = 'PurchaseShippingNotification'
end

	

	


