
USE [$(dbName)]
GO


INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (1, N'1', N'Medical Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (2, N'2', N'Surgical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (3, N'3', N'Consultation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (4, N'4', N'Diagnostic X-Ray', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (5, N'5', N'Diagnostic Lab', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (6, N'6', N'Radiation Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (7, N'7', N'Anesthesia', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (8, N'8', N'Surgical Assistance', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (9, N'9', N'Other Medical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (10, N'10', N'Blood Charges', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (11, N'11', N'Used Durable Medical Equipment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (12, N'12', N'Durable Medical Equipment Purchase', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (13, N'13', N'Ambulatory Service Center Facility', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (14, N'14', N'Renal Supplies in the Home', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (15, N'15', N'Alternate Method Dialysis', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (16, N'16', N'Chronic Renal Disease (CRD) Equipment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (17, N'17', N'Pre-Admission Testing', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (18, N'18', N'Durable Medical Equipment Rental', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (19, N'19', N'Pneumonia Vaccine', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (20, N'20', N'Second Surgical Opinion', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (21, N'21', N'Third Surgical Opinion', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (22, N'22', N'Social Work', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (23, N'23', N'Diagnostic Dental', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (24, N'24', N'Periodontics', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (25, N'25', N'Restorative', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (26, N'26', N'Endodontics', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (27, N'27', N'Maxillofacial Prosthetics', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (28, N'28', N'Adjunctive Dental Services', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (29, N'30', N'Health Benefit Plan Coverage', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (30, N'31', N'Benefit Disclaimer', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (31, N'32', N'Plan Waiting Period', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (32, N'33', N'Chiropractic', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (33, N'34', N'Chiropractic Office Visits', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (34, N'35', N'Dental Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (35, N'36', N'Dental Crowns', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (36, N'37', N'Dental Accident', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (37, N'38', N'Orthodontics', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (38, N'39', N'Prosthodontics', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (39, N'40', N'Oral Surgery', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (40, N'41', N'Routine Preventive Dental', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (41, N'42', N'Home Health Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (42, N'43', N'Home Health Prescriptions', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (43, N'44', N'Home Health Visits', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (44, N'45', N'Hospice', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (45, N'46', N'Respite Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (46, N'47', N'Hospital', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (47, N'48', N'Hospital - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (48, N'49', N'Hospital - Room and Board', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (49, N'50', N'Hospital - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (50, N'51', N'Hospital - Emergency Accident', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (51, N'52', N'Hospital - Emergency Medical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (52, N'53', N'Hospital - Ambulatory Surgical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (53, N'54', N'Long Term Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (54, N'55', N'Major Medical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (55, N'56', N'Medically Related Transportation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (56, N'57', N'Air Transportation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (57, N'58', N'Cabulance', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (58, N'59', N'Licensed Ambulance', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (59, N'60', N'General Benefits', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (60, N'61', N'In-vitro Fertilization', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (61, N'62', N'MRI/CAT Scan', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (62, N'63', N'Donor Procedure', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (63, N'64', N'Acupuncture', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (64, N'65', N'Newborn Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (65, N'66', N'Pathology', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (66, N'67', N'Smoking Cessation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (67, N'68', N'Well Baby Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (68, N'69', N'Maternity', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (69, N'70', N'Transplants', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (70, N'71', N'Audiology Exam', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (71, N'72', N'Inhalation Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (72, N'73', N'Diagnostic Medical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (73, N'74', N'Private Duty Nursing', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (74, N'75', N'Prosthetic Device', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (75, N'76', N'Dialysis', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (76, N'77', N'Otological Exam', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (77, N'78', N'Chemotherapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (78, N'79', N'Allergy Testing', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (79, N'80', N'Immunizations', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (80, N'81', N'Routine Physical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (81, N'82', N'Family Planning', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (82, N'83', N'Infertility', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (83, N'84', N'Abortion', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (84, N'85', N'HIV - AIDS Treatment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (85, N'86', N'Emergency Services', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (86, N'87', N'Cancer Treatment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (87, N'88', N'Pharmacy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (88, N'89', N'Free Standing Prescription Drug', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (89, N'90', N'Mail Order Prescription Drug', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (90, N'91', N'Brand Name Prescription Drug', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (91, N'92', N'Generic Prescription Drug', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (92, N'93', N'Podiatry', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (93, N'94', N'Podiatry - Office Visits', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (94, N'95', N'Podiatry - Nursing Home Visits', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (95, N'96', N'Professional (Physician)', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (96, N'97', N'Anesthesiologist', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (97, N'98', N'Professional (Physician) Visit - Office', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (98, N'99', N'Professional (Physician) Visit - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (99, N'A0', N'Professional (Physician) Visit - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (100, N'A1', N'Professional (Physician) Visit - Nursing Home', 1)

INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (101, N'A2', N'Professional (Physician) Visit - Skilled Nursing Facility', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (102, N'A3', N'Professional (Physician) Visit - Home', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (103, N'A4', N'Psychiatric', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (104, N'A5', N'Psychiatric - Room and Board', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (105, N'A6', N'Psychotherapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (106, N'A7', N'Psychiatric - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (107, N'A8', N'Psychiatric - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (108, N'A9', N'Rehabilitation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (109, N'AA', N'Rehabilitation - Room and Board', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (110, N'AB', N'Rehabilitation - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (111, N'AC', N'Rehabilitation - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (112, N'AD', N'Occupational Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (113, N'AE', N'Physical Medicine', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (114, N'AF', N'Speech Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (115, N'AG', N'Skilled Nursing Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (116, N'AH', N'Skilled Nursing Care - Room and Board', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (117, N'AI', N'Substance Abuse', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (118, N'AJ', N'Alcoholism Treatment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (119, N'AK', N'Drug Addiction', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (120, N'AL', N'Optometry Vision', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (121, N'AM', N'Frames', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (122, N'AN', N'Routine Exam', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (123, N'AO', N'Lenses', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (124, N'AP', N'Routine Eye Exam', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (125, N'AQ', N'Nonmedically Necessary Physical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (126, N'AR', N'Experimental Drug Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (127, N'B1', N'Burn Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (128, N'B2', N'Brand Name Prescription Drug - Formulary', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (129, N'B3', N'Brand Name Prescription Drug - Non-Formulary', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (130, N'BA', N'Independent Medical Evaluation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (131, N'BB', N'Psychiatric Treatment Partial Hospitalization', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (132, N'BC', N'Day Care (Psychiatric)', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (133, N'BD', N'Cognitive Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (134, N'BE', N'Massage Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (135, N'BF', N'Pulmonary Rehabilitation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (136, N'BG', N'Cardiac Rehabilitation', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (137, N'BH', N'Pediatric', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (138, N'BI', N'Nursery Room and Board', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (139, N'BJ', N'Skin', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (140, N'BK', N'Orthopedic', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (141, N'BL', N'Cardiac', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (142, N'BM', N'Lymphatic', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (143, N'BN', N'Gastrointestinal', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (144, N'BP', N'Endocrine', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (145, N'BQ', N'Neurology', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (146, N'BR', N'Eye', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (147, N'BS', N'Invasive Procedures', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (148, N'BT', N'Gynecological', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (149, N'BU', N'Obstetrical', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (150, N'BV', N'Obstetrical/Gynecological', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (151, N'BW', N'Mail Order Prescription Drug: Brand Name', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (152, N'BX', N'Mail Order Prescription Drug: Generic', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (153, N'BY', N'Physician Visit - Sick', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (154, N'BZ', N'Physician Visit - Well', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (155, N'C1', N'Coronary Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (156, N'CA', N'Private Duty Nursing - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (157, N'CB', N'Private Duty Nursing - Home', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (158, N'CC', N'Surgical Benefits - Professional (Physician)', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (159, N'CD', N'Surgical Benefits - Facility', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (160, N'CE', N'Mental Health Provider - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (161, N'CF', N'Mental Health Provider - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (162, N'CG', N'Mental Health Facility - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (163, N'CH', N'Mental Health Facility - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (164, N'CI', N'Substance Abuse Facility - Inpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (165, N'CJ', N'Substance Abuse Facility - Outpatient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (166, N'CK', N'Screening X-ray', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (167, N'CL', N'Screening laboratory', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (168, N'CM', N'Mammogram: High Risk Patient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (169, N'CN', N'Mammogram: Low Risk Patient', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (170, N'CO', N'Flu Vaccination', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (171, N'CP', N'Eyewear Accessories', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (172, N'CQ', N'Case Management', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (173, N'DG', N'Dermatology', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (174, N'DM', N'Durable Medical Equipment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (175, N'DS', N'Diabetic Supplies', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (176, N'GF', N'Generic Prescription Drug - Formulary', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (177, N'GN', N'Generic Prescription Drug - Non-Formulary', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (178, N'GY', N'Allergy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (179, N'IC', N'Intensive Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (180, N'MH', N'Mental Health', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (181, N'NI', N'Neonatal Intensive Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (182, N'ON', N'Oncology', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (183, N'PT', N'Physical Therapy', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (184, N'PU', N'Pulmonary', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (185, N'RN', N'Renal', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (186, N'RT', N'Residential Psychiatric treatment', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (187, N'TC', N'Transitional Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (188, N'TN', N'Transitional Nursery Care', 1)
INSERT [dbo].[TblInsuranceServiceType] ([InsuranceServiceTypeId], [Code], [Name], [IsActive]) VALUES (189, N'UC', N'Urgent Care', 1)

