namespace Falcon.App.Core.Medical.Enum
{
    public enum ReadingLabels
    {
        TotalCholestrol = 1,
        Glucose = 2,
        HDL = 3,
        TriGlycerides = 4,
        LDL = 5,
        TCHDLRatio = 6,
        FraminghamRisk = 7,
        ALT = 8,
        AST = 9,
        VentRate = 10,
        RRInterval = 11,
        PRInterval = 12,
        QRSDuration = 13,
        QTInterval = 14,
        QTcInterval = 15,
        QTDispersion = 16,
        PRTAxisQRSFront = 17,
        PRTAxisPFront = 18,
        PRTAxisTFront = 19,
        Smoker = 20,
        Diabetes = 21,
        Hba1c = 25,
        SystolicRight = 22,
        DiastolicRight = 23,
        Age = 24,
        SinusRythm = 26,
        SinusArrythmia = 27,
        SinusBradycardia = 28,
        Mild = 29,
        Marked = 30,
        SinusTachycardia = 31,
        AtrialFibrillation = 32,
        AtrialFlutter = 33,
        SVT = 34,
        PACs = 35,
        PVCs = 36,
        QRSWidening = 37,
        LeftAxis = 38,
        RightAxis = 39,
        AbnormalAxis = 40,
        Left = 41,
        Right = 42,
        HeartBlock = 43,
        TypeI = 44,
        TypeII = 45,
        FirstDegreeBlock = 46,
        ThirdDegreeCompleteHeartBlock = 47,
        Artifact = 48,
        Gender = 49,
        AortaSize = 50,
        IsFusiform = 51,
        IsSaccular = 52,
        RICAPSV = 53,
        RICAEDV = 54,
        LICAPSV = 55,
        LICAEDV = 56,
        RCCAPSV = 57,
        LCCAPSV = 58,
        SystolicRArm = 59,
        SystolicRAnkle = 60,
        SystolicLArm = 61,
        SystolicLAnkle = 62,
        RightABI = 63,
        LeftABI = 64,
        ASI = 65,
        Pattern = 66,
        EstimatedTScore = 67,
        RightHeelTScore = 68,
        LeftHeelTScore = 69,
        Pulse = 70,
        PulsePressure = 71,
        RawASI = 72,
        PencilDopplerUsed = 73,

        AorticDissection = 74,
        Plaque = 75,
        Thrombus = 76,
        TransverseViewDataPointOne = 77,
        TransverseViewDataPointTwo = 78,
        AortaRangeSaggitalView = 79,
        AortaRangeTransverseView = 80,

        EstimatedEjactionFraction = 81,
        DiastolicDysfunction = 82,
        PericardialEffusion = 83,
        VentricularEnlargement = 84,
        LeftVentricularEnlargment = 85,
        RightVentricularEnlargment = 86,
        AorticRoot = 87,
        Sclerotic = 88,
        Calcified = 89,
        Enlarged = 90,
        VentricularHypertrophy = 91,
        LeftVHypertrophy = 92,
        RightVHypertrophy = 93,
        IVSHHypertrophy = 94,
        AtrialEnlargement = 95,
        LeftAtrialEnlargment = 96,
        RightAtrialEnlargment = 97,
        Aortic = 98,
        Mitral = 99,
        Pulmonic = 100,
        Tricuspid = 101,
        AorticMorphology = 102,
        MitralMorphology = 103,
        PulmonicMorphology = 104,
        TricuspidMorphology = 105,
        Arrythmia = 106,
        ASD = 107,
        PFO = 108,
        VSD = 109,
        FlailAS = 110,
        SAM = 111,
        LVOTO = 112,
        MitralAnnularCa = 113,
        Hypokinetic = 114,
        Akinetic = 115,
        Dyskinetic = 116,
        Anterior = 117,
        Posterior = 118,

        Septal = 119,
        Lateral = 120,
        Inferior = 121,
        AoticVelocity = 122,
        MitralPT = 123,
        PulmonicVelocity = 124,
        TricuspidVelocity = 125,
        TricuspidPap = 126,

        SupraventricularArrythmia = 127,
        PacerRythm = 128,
        BundleBranchBlock = 129,
        LeftAnteriorFasicularBlock = 130,
        ProlongedQTInterval = 131,
        IschemicSTTChanges = 132,
        NonSpecificSTTChanges = 133,
        PoorRWaveProgression = 134,
        InfarctionPattern = 135,
        AtypicalQWaveLead = 136,
        RepolarizationVariant = 137,
        Apical = 138,
        SystolicLeft = 139,
        DiastolicLeft = 140,
        ReversedLeads = 141,
        RepeatStudy = 142,
        ComparetoEkg = 143,
        SystolicHighestArm = 144,
        VascularAge = 145,
        QimtLeft = 146,
        QimtRight = 147,
        ExpectedQimt = 148,
        RightEnlargedGland = 149,
        LeftEnlargedGland = 150,
        RightTissueChanges = 151,
        LeftTissueChanges = 152,
        RightNodule = 153,
        LeftNodule = 154,
        VelocityElevatedOnRight = 155,
        LeftVentricularEnlargmentValue = 156,
        RightVentricularEnlargmentValue = 157,
        LeftVHypertrophyValue = 158,
        RightVHypertrophyValue = 159,
        IVSHHypertrophyValue = 160,
        LeftAtrialEnlargmentValue = 161,
        RightAtrialEnlargmentValue = 162,
        SecondDegreeBlock = 163,
        EnlargedValue = 164,
        VelocityElevatedOnLeft = 165,
        UnabletoTechnicallyVisualize = 166,
        TechnicallyLimitedbutReadable = 167,
        TechnicallyLimitedImages = 168,
        RestrictedLeafletMotion = 169,
        RestrictedLeafletMotionAortic = 170,
        RestrictedLeafletMotionMitral = 171,
        RestrictedLeafletMotionPulmonic = 172,
        RestrictedLeafletMotionTricuspid = 173,
        LeftUnabletoOcclude = 174,
        RightUnabletoOcclude = 175,
        LowVoltage = 176,
        LimbLeads = 177,
        PrecordialLeads = 178,
        Fev1 = 179,

        High35MmHgOrGreater = 180,
        Normal = 181,

        RightCFAPSV = 182,
        RightPSFAPSV = 183,
        LeftCFAPSV = 184,
        LeftPSFAPSV = 185,

        DiagnosisCode = 186,

        AFib = 187,
        AFlutter = 188,
        PAC = 189,
        PVC = 190,

        PoorEffort = 191,
        Restrictive = 192,
        Obstructive = 193,

        PSASCR = 194,
        TSHSCR = 195,
        LCRP = 196,
        TESTSCRE = 197,

        HearingSummary = 198,
        RightEar500Hz = 199,
        LeftEar500Hz = 200,
        RightEar1000Hz = 201,
        LeftEar1000Hz = 202,
        RightEar2000Hz = 203,
        LeftEar2000Hz = 204,
        RightEar3000Hz = 205,
        LeftEar3000Hz = 206,
        RightEar4000Hz = 207,
        LeftEar4000Hz = 208,
        RightEar6000Hz = 209,
        LeftEar6000Hz = 210,
        RightEar8000Hz = 211,
        LeftEar8000Hz = 212,

        AmslerRightEye = 213,
        AmslerLeftEye = 214,
        RightEyePressure = 215,
        LeftEyePressure = 216,

        BothEyesLeftUpperQuadrant = 217,
        BothEyesLeftLowerQuadrant = 218,
        BothEyesRightUpperQuadrant = 219,
        BothEyesRightLowerQuadrant = 220,

        RightEyeLeftUpperQuadrant = 221,
        RightEyeLeftLowerQuadrant = 222,
        RightEyeRightUpperQuadrant = 223,
        RightEyeRightLowerQuadrant = 224,

        LeftEyeLeftUpperQuadrant = 225,
        LeftEyeLeftLowerQuadrant = 226,
        LeftEyeRightUpperQuadrant = 227,
        LeftEyeRightLowerQuadrant = 228,

        RightEyeCylindrical = 229,
        RightEyeSpherical = 230,
        LeftEyeCylindrical = 231,
        LeftEyeSpherical = 232,
        PeakSystolicVelocity = 233,

        RCCAProximalPSV = 234,
        RCCAProximalEDV = 235,
        RCCADistalPSV = 236,
        RCCADistalEDV = 237,
        RBulbPSV = 238,
        RBulbEDV = 239,
        RExtCarotidArtPSV = 240,
        RICADistalPSV = 241,
        RICADistalEDV = 242,
        RVertebralArtPSV = 243,
        RVertebralArtEDV = 244,

        LCCAProximalPSV = 245,
        LCCAProximalEDV = 246,
        LCCADistalPSV = 247,
        LCCADistalEDV = 248,
        LBulbPSV = 249,
        LBulbEDV = 250,
        LExtCarotidArtPSV = 251,
        LICADistalPSV = 252,
        LICADistalEDV = 253,
        LVertebralArtPSV = 254,
        LVertebralArtEDV = 255,

        Conclusion = 256,


        LeftVentricleDimensionsDilated = 257,
        LeftVentricleDimensionsSlightlyEnlarged = 258,
        LeftVentricleDimensionsNormal = 259,
        LeftVentricleDimensionsNotEvaluated = 260,
        LeftVentricleDimensionsSmall = 261,
        LeftVentricleDimensionsSeverelyDilated = 262,

        LeftVentricleOverallFunctionHyperkinesis = 263,
        LeftVentricleOverallFunctionHypokinesis = 264,
        LeftVentricleOverallFunctionReduced = 265,
        LeftVentricleOverallFunctionBorderline = 266,
        LeftVentricleOverallFunctionNormal = 267,
        LeftVentricleOverallFunctionNotEvaluated = 268,

        LeftVentricleThicknessesApicalHypertrophy = 269,
        LeftVentricleThicknessesAsymmetricalHypertrophy = 270,
        LeftVentricleThicknessesSevereIVSeptumHypertrophy = 271,
        LeftVentricleThicknessesMinorModerateIVSeptumHypertrophy = 272,
        LeftVentricleThicknessesIVSeptumObstructiveHypertrophy = 273,
        LeftVentricleThicknessesSevereSymmetricHypertrophy = 274,
        LeftVentricleThicknessesNormal = 275,
        LeftVentricleThicknessesNotEvaluated = 276,
        LeftVentricleThicknessesMinorModerateSymmetricHypertrophy = 277,
        LeftVentricleComment = 278,

        LeftAtriumIASLADimensionsMildlyDilated = 279,
        LeftAtriumIASLADimensionsSeverelyDilated = 280,
        LeftAtriumIASLADimensionsNormal = 281,
        LeftAtriumIASLADimensionsNotEvaluated = 282,
        LeftAtriumIASComment = 283,

        RightVentricleDimensionsDilated = 284,
        RightVentricleDimensionsSlightlyEnlarged = 285,
        RightVentricleDimensionsNormal = 286,
        RightVentricleDimensionsNotEvaluated = 287,
        RightVentricleDimensionsSmall = 288,
        RightVentricleDimensionsSeverelyDilated = 289,

        RightVentricleOverallFunctionHyperkinesis = 290,
        RightVentricleOverallFunctionHypokinesis = 291,
        RightVentricleOverallFunctionReduced = 292,
        RightVentricleOverallFunctionBorderline = 293,
        RightVentricleOverallFunctionNormal = 294,
        RightVentricleOverallFunctionNotEvaluated = 295,

        RightVentricleThicknessesApicalHypertrophy = 296,
        RightVentricleThicknessesAsymmetricalHypertrophy = 297,
        RightVentricleThicknessesSevereIVSeptumHypertrophy = 298,
        RightVentricleThicknessesMinorModerateIVSeptumHypertrophy = 299,
        RightVentricleThicknessesIVSeptumObstructiveHypertrophy = 300,
        RightVentricleThicknessesSevereSymmetricHypertrophy = 301,
        RightVentricleThicknessesNormal = 302,
        RightVentricleThicknessesNotEvaluated = 303,
        RightVentricleThicknessesMinorModerateSymmetricHypertrophy = 304,
        RightVentricleComment = 305,

        RightAtriumRADimensionsMildlyDilated = 306,
        RightAtriumRADimensionsSeverelyDilated = 307,
        RightAtriumRADimensionsNormal = 308,
        RightAtriumRADimensionsNotEvaluated = 309,
        RightAtriumComment = 310,

        //Aorta
        AortaInsufficiencyAbsent = 311,
        AortaInsufficiencySevere = 312,
        AortaInsufficiencyMinor = 313,
        AortaInsufficiencyModerate = 314,

        AortaValveSinusValsalvaAneurysm = 315,
        AortaValveDilatedAorticRoot = 316,
        AortaValveAtherosclerotic = 317,

        PulmonaryInsufficiencyAbsent = 318,
        PulmonaryInsufficiencyMinor = 319,

        AortaValveBicuspid = 320,
        AortaValveNotEvaluated = 321,
        AortaValveMalfunctioningBiologicalProsthesis = 322,
        AortaValveNormalFunctioningBiologicalProsthesis = 323,
        AortaValveMalfunctioningMechanicalProsthesis = 324,
        AortaValveNormalFunctioningMechanicalProsthesis = 325,

        PulmonaryInsufficiencyModerate = 326,
        PulmonaryInsufficiencySevere = 327,
        PulmonaryLeafletsNormal = 328,
        PulmonaryLeafletsThickened = 329,
        PulmonaryLeafletsStenotic = 330,

        PulmonaryValveMalfunctioningBiologicalProsthesis = 331,
        PulmonaryValveMalfunctioningMechanicalProsthesis = 332,

        AortaComment = 333,

        TricuspidInsufficiencyAbsent = 334,
        TricuspidInsufficiencyMinor = 335,

        MitralLeafletsNormal = 336,
        MitralLeafletsNotEvaluated = 337,
        MitralLeafletsRedundant = 338,
        MitralInsufficiencyAbsent = 339,
        MitralInsufficiencySevere = 340,
        MitralInsufficiencyMinor = 341,
        MitralInsufficiencyModerate = 342,

        TricuspidInsufficiencyModerate = 343,

        MitralValveMalfunctioningBiologicalProsthesis = 344,
        MitralValveMalfunctioningMechanicalProsthesis = 345,
        MitralValveBicuspid = 346,
        MitralValveAtherosclerotic = 347,
        MitralValveNormalFunctioningBiologicalProsthesis = 348,
        MitralValveNormalFunctioningMechanicalProsthesis = 349,

        TricuspidInsufficiencySevere = 350,
        TricuspidLeafletsNormal = 351,

        MitralValveNotEvaluated = 352,
        MitralValveComment = 363,

        PulmonaryValveNotEvaluated = 353,
        PulmonaryValveBicuspid = 354,
        PulmonaryValveAtherosclerotic = 355,
        PulmonaryValveNormalFunctioningBiologicalProsthesis = 356,
        PulmonaryValveNormalFunctioningMechanicalProsthesis = 357,
        PulmonaryComment = 364,

        TricuspidLeafletsThickened = 358,
        TricuspidLeafletsRedundant = 359,

        TricuspidValveNotEvaluated = 360,
        TricuspidValveBicuspid = 361,
        TricuspidValveAtherosclerotic = 362,
        TricuspidComment = 365,

        LeftAtriumIASLADimensionsModeratelyDilated = 366,
        RightAtriumRADimensionsModeratelyDilated = 367,

        TricuspidValveNormalFunctioningBiologicalProsthesis = 368,
        TricuspidValveNormalFunctioningMechanicalProsthesis = 369,
        TricuspidValveMalfunctioningBiologicalProsthesis = 370,
        TricuspidValveMalfunctioningMechanicalProsthesis = 371,

        PeakGradient = 372,

        AortaLeafletsNotEvaluated = 373,
        AortaLeafletsNormal = 374,
        AortaLeafletsMildStenosis = 375,
        AortaLeafletsModerateStenosis = 376,
        AortaLeafletsSevereStenosis = 377,

        MitralLeafletsMildStenosis = 378,
        MitralLeafletsModerateStenosis = 379,
        MitralLeafletsSevereStenosis = 380,

        PulmonaryLeafletsMildStenosis = 381,
        PulmonaryLeafletsModerateStenosis = 382,
        PulmonaryLeafletsSevereStenosis = 383,

        TricuspidLeafletsMildStenosis = 384,
        TricuspidLeafletsModerateStenosis = 385,
        TricuspidLeafletsSevereStenosis = 386,

        AorticEstimatedValveArea = 387,
        MitralEstimatedValveArea = 388,
        PulmonicEstimatedValveArea = 389,
        TricuspidEstimatedValveArea = 390,

        ConsiderOtherModalities = 391,
        AdditionalImagesNeeded = 392,

        VitD = 393,
        BloodPressureElevated = 394,
        RightArmBpMeasurement = 395,
        Hemoglobin = 396,

        ResidualLumenTransverseViewDataPointOne = 397,
        ResidualLumenTransverseViewDataPointTwo = 398,
        PeakSystolicVelocitySaggitalView = 399,

        AorticEstimatedRightValve = 400,
        MitralEstimatedRightValve = 401,
        DiastolicDysfunctionEeRatio = 402,
        ShortPrInterval = 403,

        RightFootYes = 404,
        RightFootNo = 405,
        LeftFootYes = 406,
        LeftFootNo = 407,

        Amplitude = 408,
        ConductionVelocity = 409,

        WeberNormal = 410,
        WeberAbnormal = 411,
        RinneNormal = 412,
        RinneAbnormal = 413,

        RightLeg = 414,
        LeftLeg = 415,
        RightHandBFI = 416,
        LeftHandBFI = 417,

        FunctionalAssessmentScore = 418,
        PainAssessmentScore = 419,
        MemoryRecallScore = 420,
        ClockPass = 421,
        ClockFail = 422,
        GaitPass = 423,
        GaitFail = 424,

        MonofilamentRightFootSensationIntact = 425,
        MonofilamentRightFootSensationNotIntact = 426,
        MonofilamentLeftFootSensationIntact = 427,
        MonofilamentLeftFootSensationNotIntact = 428,

        Phq9Score = 429,

        IFOBTSerialKey = 430,
        MicroalbuminSerialKey = 431,
        AscendingAortaArch = 432,
        Atherosclerosis = 433,

        FluShotManufacturer = 434,
        FluShotLotNumber = 435,

        AwvFluShotManufacturer = 436,
        AwvFluShotLotNumber = 437,

        PneumococcalManufacturer = 438,
        PneumococcalLotNumber = 439,

        LeftNoVisualPlaque = 440,
        LeftVisuallyDemonstratedPlaque = 441,
        LeftModerateStenosis = 442,
        LeftPossibleOcclusion = 443,

        RightNoVisualPlaque = 444,
        RightVisuallyDemonstratedPlaque = 445,
        RightModerateStenosis = 446,
        RightPossibleOcclusion = 447,

        DiabeticRetinopathySuspectedVeinOcclusion = 448,
        DiabeticRetinopathySuspectedWetAmd = 449,
        DiabeticRetinopathySuspectedHtnRetinopathy = 450,
        DiabeticRetinopathySuspectedEpiretinalMembrane = 451,
        DiabeticRetinopathySuspectedMacularHole = 452,
        DiabeticRetinopathySuspectedCataract = 453,
        DiabeticRetinopathySuspectedOtherDisease = 454,
        DiabeticRetinopathySuspectedGlaucoma = 455,
        DiabeticRetinopathySuspectedDryAmd = 456,
        DiabeticRetinopathyHighestLevelOfSpecificity = 457,
        MacularEdemaHighestLevelOfSpecificity = 458,

        MicroalbuminValue = 459,

        DpnAmplitude = 460,
        DpnConductionVelocity = 461,

        DpnRightLeg = 462,
        DpnLeftLeg = 463,

        ConsistentLvDiastolicFailure = 464,
        ConsistentHypertensiveHeartDiseaseWithDiastolicHeartFailure = 465,
        ConsistentHypertensiveHeartDiseaseWithoutDiastolicHeartFailure = 466,
        LeftVentricleOverallFunctionConsistentLvSystolicFailure = 467
    }
}